export declare const GameViewId: {
    PLAY_TAB_IMAGE: string;
    PLAY_TAB_IMAGE_TITLE: string;
    PLAY_TAB_TIME: string;
    PLAY_TAB_CHEAT_BUTTONS_CONT: string;
    PLAY_TAB_CHEAT_HINT: string;
    PLAY_TAB_CHEAT_REMOVE: string;
    PLAY_TAB_ANSWER_LETTERS: string;
    PLAY_TAB_AVAILABLE_LETTERS: string;
    PLAY_TAB_CORRECT_AVAILABLE_LETTER_1: string;
    PLAY_TAB_CORRECT_AVAILABLE_LETTER_2: string;
    PLAY_TAB_CORRECT_AVAILABLE_LETTER_3: string;
    PLAY_TAB_CORRECT_AVAILABLE_LETTER_4: string;
    PLAY_TAB_CORRECT_AVAILABLE_LETTER_5: string;
    PLAY_TAB_INCORRECT_AVAILABLE_LETTER_1: string;
    PLAY_TAB_CHEAT_REMOVE_AVAILABLE_LETTER_1: string;
    PLAY_TAB_ANSWER_LETTER_1: string;
    PLAY_TAB_CHEAT_HINT_ANSWER_LETTER_1: string;
};
