import { BaseObjectWithGlobalDispatcher } from "@flashist/appframework/base/BaseObjectWithGlobalDispatcher";
import { ContainersManager } from "@flashist/appframework/containers/managers/ContainersManager";
import { DeepReadonly } from "@flashist/appframework/state/data/DeepReadableTypings";
import { DisplayObjectContainer, FContainer, FLabel, Graphics, Rectangle } from "@flashist/flibs";
import { ITutorialStepConfigVO } from "../data/state/ITutorialStepConfigVO";
import { TutorialStepConfigsModuleState } from "../data/state/TutorialStepConfigsModuleState";
export declare class TutorialStepController extends BaseObjectWithGlobalDispatcher {
    protected tutorialStepConfigsState: DeepReadonly<TutorialStepConfigsModuleState>;
    protected containersManager: ContainersManager;
    stepId: string;
    stepConfig: DeepReadonly<ITutorialStepConfigVO>;
    protected stepViewContBounds: Rectangle;
    protected stepViewCont: FContainer;
    protected stepBg: Graphics;
    protected stepBlockingHoleBg: Graphics;
    protected stepScaledCont: FContainer;
    protected stepLabel: FLabel;
    protected targetViewHolePadding: number;
    protected stepInfoToViewPadding: number;
    protected targetView: DisplayObjectContainer;
    protected targetViewBounds: Rectangle;
    protected prevTargetViewBounds: Rectangle;
    protected updateTargetViewTimeout: any;
    protected activatePromise: Promise<void>;
    protected activatePromiseResolve: Function;
    protected isActive: boolean;
    protected startTime: number;
    constructor(stepId: string);
    protected construction(stepId: string): void;
    destruction(): void;
    protected addListeners(): void;
    protected onGlobalEventToComplete(): void;
    protected onStageTap(): void;
    protected processEventToComplete(): void;
    activate(): Promise<void>;
    protected complete(): void;
    protected createContent(): void;
    protected updateTutorialView(): void;
}
